apiVersion: v1
kind: Service
metadata:
  labels:
    repo: wombat
  name: wombat-ssh
  namespace: lol-staging
spec:
  # loadBalancerSourceRanges:
  # - 0.0.0.0/0
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    repo: wombat
  type: NodePort
