apiVersion: v1
kind: Service
metadata:
  labels:
    repo: wombat
  name: wombat
  namespace: lol-prod
spec:
  # loadBalancerSourceRanges:
  # - 0.0.0.0/0
  ports:
  - name: wombat
    port: 8080
    targetPort: 8080
  selector:
    repo: wombat
  sessionAffinity: ClientIP
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    repo: wombat
  name: wombat
  namespace: lol-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      repo: wombat
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        repo: wombat
      namespace: wombat
    spec:
      containers:
      - env:
        - name: WOMBAT_NODENAME
          value: "wombat@0.0.0.0"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: us.gcr.io/gigalixir-152404/gigalixir-wombat
        imagePullPolicy: Always
        name: wombat
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/service-upstream: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  name: wombat-lol-prod-gigalixirapp
  namespace: lol-prod
spec:
  rules:
  - host: wombat-lol-prod.gigalixirapp.com
    http:
      paths:
      - backend:
          serviceName: wombat
          servicePort: 8080
        path: /
